### ISSUE TITLE
Figure out a file distribution server

### ISSUE THREAD

**Issue by RumailM** [RumailM/drivebynarratives#3]
We need to have a back-end that stores the database of stories. Need to figure out an intelligent way of catering to the requests by the clients for new relevant stories. Perhaps this will be a get request to the webserver in which it receives a list of stories and their locational context. The app could then sift through what stories are redundant and which ones are not and then request to download these stories.

Look into [Firebase](https://firebase.google.com/) and [MongoDB](https://www.mongodb.com/).

**Comment by um22** [comment]
Using firebase cloudstore as the database.
